
package com.uniyaz;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-26T16:44:18.146+03:00
 * Generated source version: 3.3.4
 *
 */
public final class UserService_UserServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.service.cinema.uniyaz.com/", "UserServiceImplService");

    private UserService_UserServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UserServiceImplService ss = new UserServiceImplService(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServicePort();

        {
        System.out.println("Invoking saveUser...");
        com.uniyaz.UserDto _saveUser_arg0 = null;
        com.uniyaz.UserDto _saveUser__return = port.saveUser(_saveUser_arg0);
        System.out.println("saveUser.result=" + _saveUser__return);


        }

        System.exit(0);
    }

}
