package com.uniyaz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-26T16:44:18.196+03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://soap.service.cinema.uniyaz.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @Action(input = "http://soap.service.cinema.uniyaz.com/UserService/saveUserRequest", output = "http://soap.service.cinema.uniyaz.com/UserService/saveUserResponse")
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://soap.service.cinema.uniyaz.com/", className = "com.uniyaz.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://soap.service.cinema.uniyaz.com/", className = "com.uniyaz.SaveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.uniyaz.UserDto saveUser(

        @WebParam(name = "arg0", targetNamespace = "")
        com.uniyaz.UserDto arg0
    );
}
